"""projects scenes objects commands

Revision ID: 40227cae984c
Revises: daaa52a4e4eb
Create Date: 2026-08-28 19:07:00.241824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40227cae984c'
down_revision: Union[str, Sequence[str], None] = 'daaa52a4e4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('primary_scene_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_scene_id'], ['scenes.id'], name='fk_projects_primary_scene', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('mesh_path', sa.String(), nullable=True),
    sa.Column('pointcloud_path', sa.String(), nullable=True),
    sa.Column('occupancy_path', sa.String(), nullable=True),
    sa.Column('map_preview_path', sa.String(), nullable=True),
    sa.Column('transform_path', sa.String(), nullable=True),
    sa.Column('grid_resolution', sa.Float(), nullable=True),
    sa.Column('grid_origin_x', sa.Float(), nullable=True),
    sa.Column('grid_origin_z', sa.Float(), nullable=True),
    sa.Column('grid_width', sa.Integer(), nullable=True),
    sa.Column('grid_height', sa.Integer(), nullable=True),
    sa.Column('floor_y', sa.Float(), nullable=True),
    sa.Column('ceiling_y', sa.Float(), nullable=True),
    sa.Column('is_reflected', sa.Boolean(), nullable=False),
    sa.Column('robot_start_x', sa.Float(), nullable=True),
    sa.Column('robot_start_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('user_text', sa.String(), nullable=False),
    sa.Column('parsed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commands_scene_id_created_at', 'commands', ['scene_id', 'created_at'], unique=False)
    op.create_table('scene_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('pos_z', sa.Float(), nullable=False),
    sa.Column('bbox_min_x', sa.Float(), nullable=False),
    sa.Column('bbox_min_y', sa.Float(), nullable=False),
    sa.Column('bbox_min_z', sa.Float(), nullable=False),
    sa.Column('bbox_max_x', sa.Float(), nullable=False),
    sa.Column('bbox_max_y', sa.Float(), nullable=False),
    sa.Column('bbox_max_z', sa.Float(), nullable=False),
    sa.Column('num_views', sa.Integer(), nullable=False),
    sa.Column('num_points', sa.Integer(), nullable=False),
    sa.Column('is_fragment', sa.Boolean(), nullable=False),
    sa.Column('mesh_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_objects_name'), 'scene_objects', ['name'], unique=False)
    op.create_index(op.f('ix_scene_objects_scene_id'), 'scene_objects', ['scene_id'], unique=False)
    op.add_column('videos', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    op.create_foreign_key(
        'videos_project_id_fkey', 'videos', 'projects', ['project_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###

    # NOT part of autogenerate's output: `primary_scene_id`'s ForeignKeyConstraint was
    # declared with use_alter=True (required for the projects<->scenes circular reference),
    # which correctly excludes it from `projects`' inline CREATE TABLE, but nothing then
    # adds it via ALTER TABLE - op.create_table() doesn't replay use_alter constraints the
    # way MetaData.create_all()'s dependency-sorting does. Add it explicitly, now that both
    # tables exist.
    op.create_foreign_key(
        'fk_projects_primary_scene',
        'projects',
        'scenes',
        ['primary_scene_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the two hand-added use_alter / circular FKs first (reverse creation order).
    op.drop_constraint('fk_projects_primary_scene', 'projects', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_project_id_fkey', 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_column('videos', 'project_id')
    op.drop_index(op.f('ix_scene_objects_scene_id'), table_name='scene_objects')
    op.drop_index(op.f('ix_scene_objects_name'), table_name='scene_objects')
    op.drop_table('scene_objects')
    op.drop_index('ix_commands_scene_id_created_at', table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_table('projects')
    # ### end Alembic commands ###
