"""add usd_path to scenes

Revision ID: a1b17077b84f
Revises: 26549ef37596
Create Date: 2026-08-29 21:49:54.361798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b17077b84f'
down_revision: Union[str, Sequence[str], None] = '26549ef37596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('usd_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'usd_path')
    # ### end Alembic commands ###
