"""add per-upload blur/similarity threshold overrides to videos

Revision ID: 08ea845095a1
Revises: 40227cae984c
Create Date: 2026-08-28 21:27:49.046794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ea845095a1'
down_revision: Union[str, Sequence[str], None] = '40227cae984c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('blur_threshold', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('similarity_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'similarity_threshold')
    op.drop_column('videos', 'blur_threshold')
    # ### end Alembic commands ###
