"""add oversized_object_warning to scenes

Revision ID: 52dd0a2d3ffa
Revises: 6c4120308ca8
Create Date: 2026-09-01 21:26:28.837789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dd0a2d3ffa'
down_revision: Union[str, Sequence[str], None] = '6c4120308ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('oversized_object_warning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'oversized_object_warning')
    # ### end Alembic commands ###
