"""add reflective-floor clip diagnostics to scenes

Revision ID: 26549ef37596
Revises: 08ea845095a1
Create Date: 2026-08-28 22:02:11.953416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26549ef37596'
down_revision: Union[str, Sequence[str], None] = '08ea845095a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('points_below_floor_frac', sa.Float(), nullable=True))
    # server_default needed: existing scene rows predate this column, so a bare NOT NULL
    # add would fail; every pre-existing scene was processed before this diagnostic
    # existed, so "not suspected" is the correct backfill, not just a technicality.
    op.add_column(
        'scenes',
        sa.Column('reflective_floor_suspected', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'reflective_floor_suspected')
    op.drop_column('scenes', 'points_below_floor_frac')
    # ### end Alembic commands ###
